use_frameworks!

target 'QNStringCrypto_Example' do
  pod 'QNStringCrypto', :path => '../'

  target 'QNStringCrypto_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
