use_frameworks!

pod 'QNStringCrypto', :path => '../'

target 'QNStringCrypto_Example' do

  target 'QNStringCrypto_Tests' do
    inherit! :search_paths
  end
end

target 'QNStringCrypto-Mac' do
  target 'QNStringCrypto-MacTests' do
    inherit! :search_paths
  end
end
